# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - $(npm bin)/update-branch --commands "npm install && npm run build"
                             --commit-message "Hey GitHub, this content is for you! [skip ci]"
                             --directory "build"
                             --distribution-branch "gh-pages"
                             --source-branch "master"

env:
  global:
    - CXX=g++-4.8
    - secure: "wNVRM+7xqPnQy1hv0YtrojUJf+df5DjlvuLr/lY43hSieTgrkqrCLH50XP62HisxonKuVYqpgFI+bmJjICitz4UbbdkOA8xtAm6ST2SZv9gSftg5QeaU8YJ9w9rpV949mM2jFTkdtksDRVenPxUSkDNvtGcvGhiHogZYp9rlts2KS0lOV6j5DhsDcFb8pZtQ2vJ38nzAtMjL702qWXqo39ZBDRHC0LsLchElLPswaYI2ogMy9XsWrzmSN3oM/kquAT9fy4tiALKYruv3cWqxtfVHqEsosJSdMwVKRrHE7maDHggSzCK/90Rxz56eAVAvu6u+GAvxgFJEFL9HpJp9ccB/KVqP+3/SVb0sUi8g3aewBnP9Cw/hHlnQdrFAta6TSnWXbhe5iYnIe8GEIWqoHeFOG/LeuxgSa8aJNdijZjaQy88q83vhmUtRFiVTaxGi79BEgiyy0Za3RuQWcKJrYWZskjH9zWAznOf9LcErDi7q0ZwiSUQ1UHNaH+b4Iw/YDJg8/4bSHZro7Y2HPXYAX0hV6EjZ611N/fIAA++n0udoNHdIzL33MRdfcH+StfP2yhSowTHBOjfilcYoX3pCvqtMhXSqDAROdLemV5KYJVCWrxF1Fq6nSW+D4qIdsgklAOAUk1lVNGvccB/LVM9BLQ5qFKVmGZpwqkVWL1K9a7Q="

git:
  depth: 10

language: node_js

node_js:
  - "4"

script:
  - npm run check:src
  - npm run build

sudo:
  - required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master